name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./NodeJSBackend --file ./NodeJSBackend/Dockerfile --tag twittercontainerregistry.azurecr.io/nodejsbackend_backend
  
  push_to_azure_registry:
  
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        login-server: twittercontainerregistry.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Azure Container Registry Login
      run: docker push twittercontainerregistry.azurecr.io/nodejsbackend_backend
