name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:

  build_and_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: npm install
      run: npm install
    - name: tsc
      uses: icrawl/action-tsc@v1
      with:
        project: NodeJSBackend
    
    - name: Build the Docker image
      run: docker build ./NodeJSBackend --file ./NodeJSBackend/Dockerfile --tag twittercontainerregistry.azurecr.io/nodejsbackend_backend
      
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        login-server: twittercontainerregistry.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - name: Azure Container Registry Login
      run: docker push twittercontainerregistry.azurecr.io/nodejsbackend_backend
